# Generated by Django 2.2.2 on 2019-06-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190606_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='current_player',
        ),
        migrations.AddField(
            model_name='game',
            name='move_a',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='move_b',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
